import { Jost } from 'next/font/google';
import { Suspense } from 'react';
import Header from '@/components/Header';
import Loading from './loading';
import ReduxProvider from '@/redux/provider';
import './globals.css';

export let metadata = {
	title: 'Sandra Petereau | Développeuse web',
	description: 'Generated by create next app',
};

const jost = Jost({
	subsets: ['latin'],
	display: 'swap',
});

export default function RootLayout({ children }) {
	return (
		<html lang='fr' className={jost.className}>
			<body>
				<ReduxProvider>
					<Header />
					<main>
						<Suspense fallback={<Loading />}>{children}</Suspense>
					</main>
				</ReduxProvider>
			</body>
		</html>
	);
}
