import { Jost } from 'next/font/google'
import './globals.css'

export const metadata = {
    title: 'Sandra Petereau | Développeuse web',
    description: 'Generated by create next app',
}

const jost = Jost({
    subsets: ['latin'],
    display: 'swap',
})

export default function RootLayout({ children }) {
    return (
        <html lang="fr" className={jost.className}>
            <body>{children}</body>
        </html>
    )
}
